# Generated by Django 5.2.4 on 2025-08-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halal_app', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_carts', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='halal_app.cart'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='halal_app.category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal_app.customer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='halal_app.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_app.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_app.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_app.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal_app.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='halal_app.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halal_app.customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='halal_app.product'),
        ),
        migrations.AddField(
            model_name='save',
            name='user_save',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_saves', to='users.buyerprofile'),
        ),
        migrations.AddField(
            model_name='saveitem',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_product', to='halal_app.product'),
        ),
        migrations.AddField(
            model_name='saveitem',
            name='save_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_saves', to='halal_app.save'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user_cart',)},
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('user_save',)},
        ),
    ]
